In [5]:
import numpy as np
a = np.array([1,2,3], dtype='int64')#1-d
b = np.array([[8.0,6.0,3.1]])#2-d
print(a)
print(b)


[1 2 3]
[[8.  6.  3.1]]


In [9]:
# to get the no. of dimensions of the array
b.ndim

2

In [10]:
# to get size of the array
a.itemsize

8

In [8]:
#to get the shape of the array(row, column)
b.shape

(1, 3)

In [16]:
# to get the no. of elements in the array
b.size

3

In [17]:
#to get no. of bytes the array is stored in (total size)
b.nbytes

24

In [21]:
# to get the data types of the array
a.dtype

dtype('int32')

In [50]:
import numpy as np
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
# to get a specific element[r,c](index strat with 0)
c[1, -2]

13

In [45]:
# to get a specific row
c[0, ]

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
# to get a specific row
c[ : , 2]

array([ 3, 10])

In [49]:
# to get values with skip value [row, startindex:endindex:skip value]
c[0 , 1:6:2]

array([2, 4, 6])

In [50]:
# to change a value in an array
c[1 , 5] = 20
c[1 , ]

array([ 8,  9, 10, 11, 12, 20, 14])

In [51]:
#to change values in a column
c[:, 2] = 5
print(c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [52]:
#to change values in a column differently
c[:, 2] = [1,2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [36]:
#3-d
d = np.array([[[1,2,6],[3,4,5]],[[5,6,8],[7,8,9]]])
print(d)
#to get specific element (work outside in)
d[:,1,:]

[[[1 2 6]
  [3 4 5]]

 [[5 6 8]
  [7 8 9]]]


array([[3, 4, 5],
       [7, 8, 9]])

In [37]:
# to replace an element in an 3-d array
d[:, 1, :] = [[9,8,9], [8,8,8]]
d

array([[[1, 2, 6],
        [9, 8, 9]],

       [[5, 6, 8],
        [8, 8, 8]]])

In [14]:
# all 1s and 0s
np.ones((4,2,3), dtype='int32',)
np.zeros((4,2,3), dtype='int32')
#all other numbers
np.full((2,3), 45)

array([[45, 45, 45],
       [45, 45, 45]])

In [51]:
#full_like function(allows us to use the shape of previous arrays)
np.full_like(c,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [67]:
#to print random decimal values
np.random.rand(4,2,3)
#to print random int values
np.random.randint(-4,7, size=(3,3)) #(limit, size)

array([[-3, -1,  4],
       [ 4,  6, -3],
       [ 1,  3,  4]])

#####using copy function while copying arrays

In [69]:
e = np.array([1,2,3])
f = a.copy()
f[0]=100
print(e,f)

[1 2 3] [100   2   3]


Maths

In [70]:
# allows element by element by element operations
g = np.array([1,2,3])
print(g + 2)
print(g - 2)
print(g *2)
print(g / 2)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]


In [13]:
# to print a matrix
n = np.ones((5,5))
o = np.zeros((3,3))
o[1,1] = 9
n[1:4,1:4] = o
print(n)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


maths(continued)

In [18]:
h = np.array([1,2,3])
i = np.array([4,5,6])
print(h ** i)

[  1  32 729]


In [20]:
j = np.array([30,60,90])
k = np.sin(j)
k

array([-0.98803162, -0.30481062,  0.89399666])